---
- hosts: all
  sudo: yes
  vars:
  - pg_path: /library/pgsql-xs
  - packages:
    - python-pip
    - python-virtualenv
    - rrdtool-python
    - python-sqlalchemy
    - python-psycopg2
  - files_to_install:
    - src: stats-consolidation.conf
      dest: /etc/stats-consolidation.conf
    - src: stats-consolidation.logrotate
      dest: /etc/logrotate.d/stats-consolidation
    - src: stats-consolidation.cron
      dest: /etc/cron.d/stats-consolidation

  tasks:
  - name: Install required libraries and packages
    yum: name={{ item }}
         state=installed
    with_items: '{{ packages }}'

  - name: Enable postgresl access by md5 method
    lineinfile: backup=yes
                dest={{ pg_path }}/pg_hba.conf
                regexp="^host\s+statsconso"
                line="host     statsconso     statsconso     samehost     md5"
                state=present
                insertafter="^# IPv4 local connections"
                owner=postgres
                group=postgres

  - name: Restart postgresql service
    service: name=postgresql-xs
             state=restarted

  - name: Create postgres user
    postgresql_user: user=statsconso password=statsconso
    sudo: yes
    sudo_user: postgres

  - name: Create postgres database
    postgresql_db: db=statsconso owner=statsconso
    sudo: yes
    sudo_user: postgres

  - name: Install statistics-consolidation with pip
    pip: name=git+https://github.com/migonzalvar/statistics-consolidation.git@sqlalchemy-v2#egg=stats_consolidation

  - name: Install files
    template: src={{ item.src }}
              dest={{ item.dest }}
              owner=root
              group=root
              mode=0644
              backup=yes
    with_items: '{{ files_to_install }}'

  - name: Create log directory
    file: path=/var/log/statistics-consolidation
          state=directory
          group=sugar-stats
          owner=sugar-stats
          mode=0755

